### ISSUE TITLE
Add zoomable after dom update

### ISSUE THREAD

**Issue by jsantari** [marshallku/smooth-zoom#2]
I'm trying to use smooth-zoom on a site as follows. I have a list of products displayed each with a button to load more details via ajax to a new panel below the list location on the page. I can due this for as many products as I want. I call Zoom('.zoomable') after the dom updates. The problem I have is since Zoom('.zoomable') is called multiple times it appears to add events to images more then once since when I click to unzoom the image depending on how many I have loaded details for it may take several clicks to close all the zoomed layers for a specific image depending where it was in the order of being opened. Is there any way to stop this from happening? For example: if I load product 1 details it will only take 1 click to close. If I then open product 2 details it will only take one click on product 2 to close but product 1 will now take 2 clicks to unzoom. Each new load will add 1 click to unzooming for images that were already loaded.

**Comment by marshallku** [comment]
Now you can pass HTMLElment, NodeList as argument.

I know it might be inefficient or annoying to call the function everytime you update the DOM. I promise you an update as soon as possible.

**Comment by marshallku** [comment]
I just added the “attach” method.
Hope that helps you.
