### ISSUE TITLE
[Bug] zoom-ing animation isn't shown

### ISSUE THREAD

**Issue by cog25** [marshallku/smooth-zoom#3]
### What happened

When I clicked zoomable image, zoom-ing animation isn't appeared. See also [this video](https://youtu.be/5bePtpDPbp4)(include browser version, os, and etc)

p.s. unzoom-ing animation is working well.

### What browsers are you seeing the problem on?

Firefox

**Comment by marshallku** [comment]
Thanks for your report.
I've found the reason, and I'll fix it very soon.
