### ISSUE TITLE
[Request] useMaximumSize based height option

### ISSUE THREAD

**Issue by kale5195** [marshallku/smooth-zoom#4]
### Problem

Right now useMaximumSize param is based on width, this is not worked for long images..

Wonder if we can add a option based on the height for useMaximumSize

### Solution

A option to make use naturalHeight

**Comment by marshallku** [comment]
Could you tell me the exact size of the image?
It might be very helpful to resolve this issue.

**Comment by kale5195** [comment]
@marshallku  Thanks for you reply. Here is an example: https://mirror.xyz/zoroo.eth/pfen9oHGGaq09fUbsS1LQRXw3Gl2AkxToUufaIQL_oU

In this article, there is a long image:  https://images.mirror-media.xyz/publication-images/0yDketZhapYnyypIuU4fW.png?height=4518&width=780

**Comment by marshallku** [comment]
@0xhaole I tested in almost every screen size with that image, and it does work fine.
You might think that it's not working becuase it's shrinked, but fitting the image to the screen is the most important goal for this package.
